[[main]]
  name = "Home"
  pageRef = "/"
  weight = 5

[[main]]
  name = "Research"
  pageRef = "research"
  weight = 10

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 20

[[main]]
  name = "Lab Tools"
  pageRef = "lab-tools"
  weight = 30

[[main]]
  name = "Outreach"
  pageRef = "outreach"
  weight = 40

[[main]]
  name = "About"
  pageRef = "about"
  weight = 50

[[footer]]
  name = "GitHub"
  url = "https://github.com/georgeschaible"
  weight = 10

[[footer]]
  name = "Bluesky"
  url = "https://bsky.app/profile/quantaofgeorge.bsky.social"
  weight = 20

[[footer]]
  name = "ORCID"
  url = "https://orcid.org/0000-0002-1031-4682"
  weight = 30

[[footer]]
  name = "RSS"
  url = "/index.xml"
  weight = 40
