description = "Microbiology, ultrastructure, and DIY scientific instruments"

author_name = "George Schaible"
affiliation_title = "Postdoctoral researcher"
affiliation_institution = "University of California, Santa Barbara"
